version: '3.7'

services:
  postgres:
    image: postgres:15.2
    restart: always 
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_db
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data

  redis-session:
    image: redis:7.0.8
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data: